// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkIhfXNejf_VIkBaMs8NDocOqNeEQGqzw',
    appId: '1:458325852900:ios:224add92f1a8c9f366e2f1',
    messagingSenderId: '458325852900',
    projectId: 'boardzone-app',
    storageBucket: 'boardzone-app.firebasestorage.app',
    iosBundleId: 'com.example.boardzoneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkIhfXNejf_VIkBaMs8NDocOqNeEQGqzw',
    appId: '1:458325852900:ios:224add92f1a8c9f366e2f1',
    messagingSenderId: '458325852900',
    projectId: 'boardzone-app',
    storageBucket: 'boardzone-app.firebasestorage.app',
    iosBundleId: 'com.example.boardzoneApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa4pTwqNBpM3xjWMTxW7GXN5u4CL-rPLM',
    appId: '1:458325852900:web:ecfc952b46f22c5e66e2f1',
    messagingSenderId: '458325852900',
    projectId: 'boardzone-app',
    authDomain: 'boardzone-app.firebaseapp.com',
    storageBucket: 'boardzone-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgTIj1ookOiaCmkpDKRy56Gmn4YXqjAPY',
    appId: '1:458325852900:android:8e6c6485020c413f66e2f1',
    messagingSenderId: '458325852900',
    projectId: 'boardzone-app',
    storageBucket: 'boardzone-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa4pTwqNBpM3xjWMTxW7GXN5u4CL-rPLM',
    appId: '1:458325852900:web:92eb63a8658b10e766e2f1',
    messagingSenderId: '458325852900',
    projectId: 'boardzone-app',
    authDomain: 'boardzone-app.firebaseapp.com',
    storageBucket: 'boardzone-app.firebasestorage.app',
  );

}